site_name: Narrion

theme: readthedocs

nav:
  # - Home: index.md
  - Instrukcja użytkownika: instruction.md
  - Analiza modeli: models.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - mkdocs-autoapi:
      autoapi_dir: narrion
      autoapi_file_patterns:
        - "*.py"